title: "FREEBASSEL"
tagline: "Campaign to FREE Bassel Khartabil"
exclude: [README.md, LICENSE.md, designs, Gemfile, Gemfile.lock, config, get_supporters_data.rb]

permalink: /campaign/:categories/:year/:month/:day/:title/

name: FREEBASSEL
description: "#FREEBASSEL is a campaign to free loved technology innovator Bassel Khartabil missing since March 15, 2012."
url: http://freebassel.org

keywords: ['freebassel', 'basselkhartabil ', 'basselsafadi', 'bassel', 'whereisbassel', 'syria', 'damascus', 'creativecommons', 'freeculture', 'sharing', 'sharism']

email: info@freebassel.org
twitter: freebassel
facebook: FreeBasselSafadi
instagram: freebassel

languages :
  en: English
  ar: Arabic

instafeed:
  tag: 'freebassel'
  client_id: '515a7d6587b249f18c9a855868e0ac1b'
  captions: true
  limit: '20'
  refresh: '60000'
